SELECT N_NAME, SUM(L_QUANTITY) AS TOTAL_ITEMS
FROM LINEITEM, ORDERS, NATION, CUSTOMER
WHERE L_ORDERKEY = O_ORDERKEY
  AND O_CUSTKEY = C_CUSTKEY
  AND N_NATIONKEY = C_NATIONKEY 
GROUP BY N_NAME 
ORDER BY TOTAL_ITEMS DESC LIMIT 10;