SELECT N_NAME, SUM(L_QUANTITY) AS TOTAL_QUANTITY
FROM NATION,CUSTOMER, ORDERS, LINEITEM 
WHERE C_NATIONKEY = N_NATIONKEY 
  AND O_CUSTKEY =C_CUSTKEY 
  AND O_ORDERKEY = L_ORDERKEY 
GROUP BY N_NAME 
HAVING TOTAL_QUANTITY > 62000 
ORDER BY TOTAL_QUANTITY DESC;