SELECT SUM(NOT_SPECIAL)
FROM (
    -- SOMA DE TODOS OS CLIENTES
    SELECT COUNT(DISTINCT C_CUSTKEY) AS NOT_SPECIAL
    FROM CUSTOMER

    UNION

    -- SOMA DE CLIENTES QUE FIZERAM UMA ORDEM COMO 'SPECIAL REQUEST'
    SELECT - COUNT(DISTINCT C_CUSTKEY) AS NOT_SPECIAL
    FROM CUSTOMER LEFT JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
    WHERE O_COMMENT LIKE '%special request%'

);
